#!/bin/bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/opt/homebrew/bin/brew shellenv)"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

brew install nvm
brew install --cask appcleaner
brew install --cask audacity
brew install --cask blu-ray-player-pro
brew install --cask chatgpt
brew install --cask gamemaker
brew install --cask google-chrome
brew install --cask notion
brew install --cask obs
brew install --cask plex
brew install --cask postman
brew install --cask vb-cable
brew install --cask visual-studio-code
brew install --cask warp
brew install --cask zoom

touch "$HOME/.personalrc"
git config --global user.name "Jonathan Lowell"
git config --global user.email "elderlowell@gmail.com"

chsh -s $(which zsh)

if [ ! -d "$HOME/Code" ]
then
  mkdir "$HOME/Code"
fi

if [ ! -d "$HOME/Git" ]
then
  mkdir -p "$HOME/Git/elderlowell-settings"
fi


if [ ! -d "$HOME/Git/mac-setup" ]
then
  git clone https://github.com/elderlowell/mac-setup.git "$HOME/Git/mac-setup"
fi

echo "Do you want to set up a new SSH key for the system? (y/n)"
read response
if [ "$response" = "y" ]
then
  new-ssh-key
else
  echo "No SSH key will be set up. You can always set one up later by running \"new-ssh-key\"."
fi